name: Maven Verify

on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 0 28 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Test and build Maven project
      run: mvn --batch-mode --update-snapshots verify --file pom.xml
    - name: Upload build artifact
      run: mkdir staging && cp target/*-jar-with-dependencies.jar staging
    - uses: actions/upload-artifact@v4
      with:
       name: EbProjectEditor
       path: staging
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: 'test0bucket-234234'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: 'staging'